### ISSUE TITLE
Compatibilité Centreon 2.5 / Nagvis 1.7

### ISSUE THREAD

**Issue by nutzmdm** [titilambert/centreon-nagvis#1]
Bonjour,
le module est-il compatible Centreon 2.5 / Nagvis 1.7 ?
Je l'ai testé et j'obtiens systématiquement le message "Le module n'est pas enregistré."

**Comment by X-dark** [comment]
Il faut patcher les fichiers de Nagvis tel que décrit dans centreon/www/modules/nagvis/install/patch
Cela étant dit, l'authent ne marche pas pour autant chez moi.

**Comment by nutzmdm** [comment]
Oulà, depuis le temps j'avais oublié ce message :) Du coup, le module fonctionne depuis un bon moment maintenant chez moi, y compris l'authentification, alors si je peux t'aider...

**Comment by X-dark** [comment]
J'utilisais des contactgroups dans les ACL, du coup la requête ne fonctionnait pas. Tout fonctionne maintenant.
